# Generated by Django 6.1.1 on 2026-09-10 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_vacancies', models.IntegerField(verbose_name='Всего активных вакансий')),
                ('median_salary', models.FloatField(verbose_name='Медианная ЗП')),
                ('avg_salary', models.FloatField(verbose_name='Средняя ЗП')),
                ('top_skills', models.JSONField(verbose_name='Топ навыков (JSON)')),
            ],
            options={
                'verbose_name': 'Ежедневная аналитика',
                'verbose_name_plural': 'Ежедневная аналитика',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название навыка')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=10, verbose_name='Уровень подписки')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название должности')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='ЗП от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='ЗП до')),
                ('salary_avg', models.FloatField(blank=True, null=True, verbose_name='Средняя ЗП')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт работы')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Удаленка')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на вакансию')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сбора')),
                ('skills', models.ManyToManyField(blank=True, related_name='vacancies', to='analytics.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
