# Generated by Django 6.1.1 on 2026-09-12 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyanalytics',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='avg_salary',
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='median_salary',
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='total_vacancies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='vacancies_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_role',
            field=models.CharField(default='Python Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('all', 'All / Not specified')], default='all', max_length=10, verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='top_skills',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
